services:
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "DSY^#A2H6FyeX^gt"
      MYSQL_DATABASE: Carbonara
      MYSQL_USER: carbonara
      MYSQL_PASSWORD: "bpx04sYqIlcVbJRC"
    volumes:
      - mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma
    restart: always
    links:
      - db
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0

  angular:
    build:
      context: ../CarbonaraAngular
      dockerfile: ../Integration/angular.dockerfile
      cache_from:
        - $IMAGE/angular
    image: $IMAGE/angular
    container_name: angular
    links:
      - webapi
    ports:
      - 8080:8080
    restart: always

  webapi:
    build:
      context: ../CarbonaraWebAPI
      dockerfile: ../Integration/webapi.dockerfile
      cache_from:
        - $IMAGE/webapi
    image: $IMAGE/webapi
    container_name: webapi
    links:
      - db
    restart: always

volumes:
  mariadb:
